### PR TITLE
Update Boxed Expression Component and Feel Input Component

### PR DESCRIPTION
**Pull request by ljmotta**

### CODE REVIEW

**Comment by yesamer** [comment]
@ljmotta Thank you. Build launched.

**Comment by yesamer** [comment]
@ljmotta One test failed on `feel-input-component`

**Comment by ljmotta** [comment]
@yesamer I've fixed the tests issue.

**Comment by yesamer** [comment]
vscode-extension-pack-kogito-kie-editors: Extension 'kie-group.vscode-extension-pack-kogito-kie-editors' was successfully uninstalled!
vscode-extension-pack-kogito-kie-editors:   Suite duration: 51.471 s, Tests: 6
vscode-extension-pack-kogito-kie-editors:   4 passing (56s)
vscode-extension-pack-kogito-kie-editors:   2 failing
vscode-extension-pack-kogito-kie-editors:   1) Editors are loading properly
vscode-extension-pack-kogito-kie-editors:        Check new DMN Expression Editor:
vscode-extension-pack-kogito-kie-editors:      NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".boxed-expression-editor"}

**Comment by yesamer** [comment]
vscode-extension-pack-kogito-kie-editors:   2) Editors are loading properly
vscode-extension-pack-kogito-kie-editors:        "after each" hook for "Check new DMN Expression Editor":
vscode-extension-pack-kogito-kie-editors:      NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".monaco-dialog-box"}

**Pull request merged**
